export const USER_SIGN_IN_BEGIN = 'USER_SIGN_IN_BEGIN';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE';
export const USER_SIGN_IN_DISMISS_ERROR = 'USER_SIGN_IN_DISMISS_ERROR';
export const USER_UPDATE_USER_BEGIN = 'USER_UPDATE_USER_BEGIN';
export const USER_UPDATE_USER_SUCCESS = 'USER_UPDATE_USER_SUCCESS';
export const USER_UPDATE_USER_FAILURE = 'USER_UPDATE_USER_FAILURE';
export const USER_UPDATE_USER_DISMISS_ERROR = 'USER_UPDATE_USER_DISMISS_ERROR';
